### ISSUE TITLE
Support arbitrary image topic names

### ISSUE THREAD

**Issue by loganzartman** [ut-amrl/robofleet_webviz#21]
We have the technology to match topic names against a regex. Why not create an image topic prefix (e.g. /myrobot/image) and display feeds from any subtopics on the imagery tab?

**Comment by kvsikand** [comment]
@loganzartman do you think https://github.com/ut-amrl/robofleet_webviz/pull/23 covers this fully?

**Comment by loganzartman** [comment]
yeah, I think we're good on this
